### PR TITLE
Initialize repo

### PR DESCRIPTION
**Pull request by samakhov**
Push first files. Some pages are functionnal. I need to reorganize more.

### CODE REVIEW

**Comment by guillep** [comment]
The PR is ok, we should change the travis file so it does not try to upload in Pull Requests.

**Comment by samakhov** [comment]
Okay, Then It is only after you merged that that travis will try to upload. Because last time I thought I broke something

**Comment by guillep** [comment]
Good work for a first upload ^^.

Regarding the failure, yes, if you want to take a look at the travis configuration, it shouldn't be difficult to fix.

Also, some feedback on your changes:
 - check that the urls are broken, you probably have to remove the baseurl
 - did you create a new theme or you just modified candy? it would be good if we can package your new theme (with the incoming modifications) in a standalone theme that we can reuse later

**Comment by samakhov** [comment]
Okay, Thanks.
I will try to look at Travis configuration.
yes for urls, I need to remove the baseurl. Perhaps this night I will do a PR for that.
Okay, good idea for the theme. I will manage for that.

**Pull request merged**
