### PR TITLE
Talk proposal for ESUG 2024.

### PR DESCRIPTION
**Pull request by offray**

### CODE REVIEW

**Comment by Ducasse** [comment]
Hi I think that this is important that
- your talks do not explode the schedule like during last ESUG 
- that they get more technical than activism based.
I like your actions but we should focus on the actions and not the theory.

**Comment by offray** [comment]
Thanks Stephan.

I do not get the first point regarding "exploding" the schedule. Could you expand on it?

While the  second talk (data landscapes) will be activism based, following your advice, I would be focusing about the technical aspects of the work we are doing. The one about teaching to non-developers is informed not only by activism but  by the undergrad and post-grad classes we are doing in the Faculty of Communication and Languages Studies, so it is more a report on the strategies we use when our target audience is not developers and/or computer scientist and the Pharo/GT based tools and curriculum we create to introduce them to computational thinking.

**Comment by Ducasse** [comment]
Just repeat your talk and make sure that it fits in 30 min.

**Comment by offray** [comment]
I will do it. [Last year ESUG talks](https://www.youtube.com/watch?v=1_PwCcTALiY&list=PLJ5nSnWzQXi8-w5MAt_Rf-OjNDtBME7nK) were between 30 minutes and almost and hour and mine fit in that range. I'll keep both of mine on the half an hour mark.

As I'm asking monetary support from my university, could I ask the merging of my talks in the official repository as the other talk PRs? Paperwork over here takes a long and if I don't have a proper acceptance by next Monday, my chances to get any fund from my University become smaller.

**Pull request merged**
